### PR TITLE
Do not merge

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@psturc should this be using the linked e2e test PR with the same branch name: https://github.com/redhat-appstudio/e2e-tests/pull/627

Not sure if the failure is an issue with the other PR or this PR just not using it.

**Comment by psturc** [comment]
@stuartwdouglas according [this log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/703/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-e2e/1678627334334189568#1:build-log.txt%3A49-61) this PR is using the related PR in e2e-tests.

According to the [logged error](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/703/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-e2e/1678627334334189568#1:build-log.txt%3A80) it failed on [this line](https://github.com/redhat-appstudio/e2e-tests/pull/627/files#diff-d7a1577b2d546e34aaf816bdd1b83edef28a66a555f049767bafa83268b7efbbR354)

**Pull request closed without merging**
