### PR TITLE
add pruning logging/eventing to aid PR debug

### PR DESCRIPTION
**Pull request by gabemontero**
see https://github.com/redhat-appstudio/e2e-tests/pull/169#issue-1332425978

### CODE REVIEW

**Comment by gabemontero** [comment]
if we are lucky, the jvm-build-service-e2e will flake in the same way it did for me earlier in infra-deployments

**Comment by gabemontero** [comment]
no luck - they passed

did see the error logs and events 

will test a time or two more tonight just in case, then merge

**Comment by gabemontero** [comment]
still clean

/test jvm-build-service-e2e

**Review by stuartwdouglas — APPROVED** [review]

**Comment by gabemontero** [comment]
the e2e failure was a appstudio bootstrap issue

that said this PR is superseded by #171 which both pulled in these changes, and then provides a plausible theory / fix to the intermittent timing window we've see with pruning on

closing this out

**Pull request closed without merging**
