### PR TITLE
Add the ability to enforce versions

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This allows for builds that are not tagged properly to still be built.

### CODE REVIEW

**Comment by Michkov** [comment]
Testing new tekton bundle which include triggers artifacts build (building on by one)

/test jvm-build-request-processor-on-pull-request

**Comment by gabemontero** [comment]
I'm good merging when ever you are @stuartwdouglas

**Review by gabemontero — APPROVED** [review]

**Comment by gabemontero** [comment]
I'll refrain from applying the lgtm label in case there were minor tweaks @stuartwdouglas wanted to do before merging

**Pull request merged**
