### PR TITLE
Fix potential resource leak in the cache

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
/test jvm-build-service-in-repo-apicurio-e2e

@gabemontero FYI

I need to spend more time on this, but this could be the root cause.

**Comment by gabemontero** [comment]
In case you didn't have a chance to look @stuartwdouglas the hang still occurred.  A bunch of 

`jvm-build-service-test-namespace-vmd6g_fba4bfcd24076fac508117e0e290a7e2-build-0-task-pod_step-build.log:[INFO] Retrying request to {}->http://jvm-build-workspace-artifact-cache.jvm-build-service-test-namespace-vmd6g.svc.cluster.local:80`

in the gather-extra pod logs

But as you said you need more time on this one.

I'm testig my change to 
a) fix the watch timeout so that it collects current state before the whole test times out
b) adding a separate "still building" category to the report generation stuff you gave us a few weeks ago so we don't have to download the entire set of pod logs via gsutil

I'll see about getting those thread dumps while I sort through a) and b)

**Comment by gabemontero** [comment]
/test jvm-build-service-in-repo-apicurio-e2e

let's confirm results with periodic test updates for better timeout / dependencybuild gathering

**Comment by gabemontero** [comment]
OK @stuartwdouglas my periodic test fixes are manifesting correct with the apicurio test in your PR here.

- timeout / collect data working
- overall status at https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/280/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-apicurio-e2e/1576927213385682944/artifacts/jvm-build-service-in-repo-apicurio-e2e/jvm-build-service-in-repo-apicurio-e2e/artifacts/jvm-build-service-report/index.html with building counts and toggles
- a couple of examples where the interaction with the artifact cache appear to be hung are at https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/280/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-apicurio-e2e/1576927213385682944/artifacts/jvm-build-service-in-repo-apicurio-e2e/jvm-build-service-in-repo-apicurio-e2e/artifacts/jvm-build-service-report/DependencyBuildStateBuilding/c98447ee5f9350de3ebdd949a887bc69c98447ee5f9350de3ebdd949a887bc69-build-0-task-podstep-build and https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/280/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-apicurio-e2e/1576927213385682944/artifacts/jvm-build-service-in-repo-apicurio-e2e/jvm-build-service-in-repo-apicurio-e2e/artifacts/jvm-build-service-report/DependencyBuildStateBuilding/f1ec184d8c48b56f6d9b5b942411d111f1ec184d8c48b56f6d9b5b942411d111-build-0-task-podstep-build

**Pull request merged**
