### PR TITLE
Update image controller

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by rnc** [comment]
Does this replace https://github.com/redhat-appstudio/jvm-build-service/pull/1761/files ? Can the baseline go be updated to 1.21?

**Comment by stuartwdouglas** [comment]
Actually I think https://github.com/redhat-appstudio/jvm-build-service/pull/1761 can be merged instead, there is no reason why we can't update the baseline AFAIK.

**Comment by stuartwdouglas** [comment]
Actually there is a problem with the e2e tests, something there is still using an old version of go.

**Comment by rnc** [comment]
> Actually there is a problem with the e2e tests, something there is still using an old version of go.

I suspect that is what is causing all the other PRs to fail in their e2e (as they all want to update the baseline go)

**Comment by stuartwdouglas** [comment]
https://github.com/openshift/release/pull/53327 might fix it

**Pull request closed without merging**
