### PR TITLE
Minikube local dev script

### PR DESCRIPTION
**Pull request by tecarter94**
Implement minikube-local-development.sh for ease of local testing. Remove redundant minikube-images.sh.

https://issues.redhat.com/browse/KJB-43

### CODE REVIEW

**Comment by rnc** [comment]
Can we delay this as some of the changes in #2062 might affect it.

**Comment by tecarter94** [comment]
> Can we delay this as some of the changes in #2062 might affect it.

Sure @rnc. I hadn't thought that'd be an issue. Happy to make any adjustments to the script once #2062 is merged.

**Comment by tecarter94** [comment]
@rnc I've updated this PR after you merged #2062.

**Comment by tecarter94** [comment]
@rnc FYI I tried removing the minikube-images script before but it somehow resulted in failed tests.

**Pull request merged**
