### PR TITLE
PLNSRVCE-658: bump(*) k8s,kcp to build-service,integration-service levels

### PR DESCRIPTION
**Pull request by gabemontero**
adjust context/clustername api usage accordingly

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
looks like you need to run `go mod vendor`.

**Comment by gabemontero** [comment]
all e2e's green; ignoring codecov nits

**Comment by stuartwdouglas** [comment]
LGTM

**Pull request merged**
