### PR TITLE
Use Shenandoah for GC

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This may also help with the CI failures.

### CODE REVIEW

**Comment by gabemontero** [comment]
appstudio bootstrap failed with in-repo

trying again

/retest

**Comment by gabemontero** [comment]
unrelated appstudio bootstrap issue nuked this run https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/144/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-e2e/1553112748081025024

/retest

**Comment by stuartwdouglas** [comment]
This does not seem to have made any difference, the actual fix was to increase CPU/memory

**Pull request closed without merging**
