### PR TITLE
Use docker build from the catalog

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@Michkov I was hoping to utilise the snyk scan to help resolve https://issues.redhat.com/browse/STONEBLD-432 but it does not actually run due to a missing secret. Do we have any way to actually run this at the moment?

**Comment by stuartwdouglas** [comment]
Actually I have just enabled dependabot, which is probably better than snyk anyway.

**Comment by Michkov** [comment]
@stuartwdouglas this bundle does not have infra-deployment-update task, we do not have new bundles yet.

**Comment by stuartwdouglas** [comment]
closing, as this does not help with 432 anyway.

**Pull request closed without merging**
