### PR TITLE
Fix variable substitution within diagnostic files

### PR DESCRIPTION
**Pull request by rnc**

### CODE REVIEW

**Comment by rnc** [comment]
@stuartwdouglas Can we hold merging this until https://github.com/apheleia-project/jbs-issues/issues/13 is resolved.

**Comment by stuartwdouglas** [comment]
I think we should move to disallowing any tekton substitution in these, and have a pre-approved / documented list of env vars instead.

**Comment by rnc** [comment]
Closing this as redundant with https://github.com/apheleia-project/jbs-build-issues/issues/13

**Pull request closed without merging**
