### PR TITLE
Add repositories for Gradle builds

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Adding these extra repos may cause some builds to slow down significantly, due to an issue with the date based filtering of 'maven-metadata.xml'.

I am going to attempt to address this today.

/test jvm-build-service-in-repo-apicurio-e2e

**Comment by dwalluck** [comment]
> /test jvm-build-service-in-repo-apicurio-e2e

The report was only showing the 4 test builds (3 test projects + asm).

**Pull request merged**
