### PR TITLE
Added a way to prepend the SHA tags for container registry

### PR DESCRIPTION
**Pull request by phillip-kruger**
So we can run multiple tests

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

**Comment by gabemontero** [comment]
S3 / AWS SDK / localstack pain during the in repo e2e; presumably with the pruning job passing this is just an env / constrain flake, but let's see if we can get clean

/test jvm-build-service-in-repo-e2e

**Comment by gabemontero** [comment]
all green ... merging

**Pull request merged**
