### PR TITLE
fix: env var typo

### PR DESCRIPTION
**Pull request by psturc**

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]
/lgtm

I had the typo in my test env too which is why this worked for me

**Comment by psturc** [comment]
@gabemontero could you please also merge? I don't have write permissions for this repo. Thanks

**Comment by gabemontero** [comment]
I was just waiting for the pac jobs to get far enough along @psturc 

double checking them now and assuming they are OK will merge

**Comment by gabemontero** [comment]
hmmm the build-req-processor one may have failed 

will retest and monitor, then merge

**Pull request merged**
