### PR TITLE
Fix PipelineRun pruning

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This fixes a potential race in the pruning of PipelineRun's. Presently these are pruned
before the relevant status update is made on the owner object. Because of the owner reference
this deletion will also update the corresponding owner, making it likely that this update
might fail. Normally failure would result in a requeue but because the oject is question
has been deleted this will no longer work properly.

This fix changes the deletion to happen after the status update, and will also prune any
PipelineRun objects that exist after the object is in its expected state. This means that
even if the prune fails a subsequent reque should allow the prune to succeed.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
First test runs was green, but I have added the logging from https://github.com/redhat-appstudio/jvm-build-service/pull/169

**Comment by stuartwdouglas** [comment]
GitHub rate limiting

/retest

**Comment by gabemontero** [comment]
these changes seem on the right path with respect to this timing issue

that said, before we merge this, I'm going to add an e2e job *in this repo* (vs. adding the test back to e2e-tests) that runs with pruning on

So we we will have e2e's with pruning off (to facilitate debug of new features) and pruning on (to vet these timing issues with pruning moving forward, or if/when we evolve to the more advanced throttling @stuartwdouglas and I have discsussed)

then when see get both positive feedback with this PR, and subsequent days (maybe a weeks worth) of positive results in other PRs with the new in repo pruning e2e, we'll revisit adding the e2e, with pruning on, back to e2e-tests

@Michkov @brunoapimentel @psturc FYI ^^

**Comment by gabemontero** [comment]
/hold

until I get that new e2e defined in openshift/release

**Comment by stuartwdouglas** [comment]
@gabemontero why do you want to hold this? The current state machine is broken with respect to failures due to pruning. I can't say for sure that it is the fix to the test issue, but we won't really know until it is merged.

**Comment by gabemontero** [comment]
> @gabemontero why do you want to hold this? The current state machine is broken with respect to failures due to pruning. I can't say for sure that it is the fix to the test issue, but we won't really know until it is merged.

Well, as far as I know, the only "things" hitting the current pruning bug is when we try to activate our e2e in https://github.com/redhat-appstudio/e2e-tests .... no stand alone human users that I know of are complaining that they are hitting this issue

So the e2e has already been commented out (again) in https://github.com/redhat-appstudio/e2e-tests so we are no longer blocking the other teams' e2e's

Now, if I am uninformed about human users hitting this on the staging cluster, then sure, let's reset and merge this.

Otherwise, adding the new e2e *shouldn't* be hard.  I'll work on the PR in a couple and hopefully @psturc can tag it for merge before he leaves today.

Then, we can get some e2e based validation (via repeated runs since it is a timing issue) yay/nay on this change.

Ideally, I can test this against the new e2e a bunch of times this afternoon and merge this by EOB for me Tuesday.

WDYT @stuartwdouglas ?

**Comment by gabemontero** [comment]
new test defined in https://github.com/openshift/release/pull/31184 ^^

**Comment by gabemontero** [comment]
ok tracking the initial in repo pruning job run https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/171/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-with-pruning-e2e/1557047676359413760

Happen to have Phillip's PNC fallback PR also running this for comparison.

**Comment by gabemontero** [comment]
ok the new pruning e2e is clean, with logs or our new pruning messages in the operator log .... let's see how consistent things are

run 2

/test jvm-build-service-in-repo-with-pruning-e2e

**Comment by gabemontero** [comment]
also our pruning off e2e had no pruning messages

**Comment by gabemontero** [comment]
appstudio bootstrap fail

/test jvm-build-service-in-repo-with-pruning-e2e

**Comment by gabemontero** [comment]
/retest

for the builder images

**Comment by gabemontero** [comment]
passed 

/test jvm-build-service-in-repo-with-pruning-e2e

**Comment by gabemontero** [comment]
passed again

going to retest again, see if we can get PaC req processor clean for potential image update the merge either way

/retest

**Comment by gabemontero** [comment]
we are running into the known PaC bug

both the jdk11 builder is complete 

jvm-build-hacbs-jdk11-builder-on-pull-request-hb5v5   True        Completed   106m        93m

as is the controller

jvm-build-hacbs-jdk11-builder-on-pull-request-hb5v5   True        Completed   106m        93m


merging

**Pull request merged**
