### PR TITLE
Remove the sidecar

### PR DESCRIPTION
**Pull request by stuartwdouglas**
All sidecar related functionality has been delegated to the cache.

### CODE REVIEW

**Review by gabemontero — CHANGES_REQUESTED** [review]
per the e2e results they appear "non-impactful", but I've got one minor cleanup request wrt openshift flows

otherwise very cool this transition will be in the books

**Comment by stuartwdouglas** [comment]
Numbers are looking good: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/263/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-apicurio-e2e/1571735582575431680/artifacts/jvm-build-service-in-repo-apicurio-e2e/jvm-build-service-in-repo-apicurio-e2e/artifacts/jvm-build-service-report/index.html

**Comment by stuartwdouglas** [comment]
One weird thing that needs further investigation is that the Netty build has passed, however the ArtifactBuild's are reported as Failed.

**Comment by gabemontero** [comment]
> One weird thing that needs further investigation is that the Netty build has passed, however the ArtifactBuild's are reported as Failed.

do you want to address ^^ with this PR or a follow up PR @stuartwdouglas ?

otherwise I'm good to merge this (in fact, it would help my kcp work to get the artifact cache permission fix that is in this PR)

**Comment by gabemontero** [comment]
forgot earlier - what is the plan for updating build-definitions and openshift release ?

although other things might break it, I would think we 
- remove side car defs from build-definitions 
- remove side car defs from openshift/release (doubt the rehearsal works since it will use super old images)
- then in a test PR here in this repo, see what the optional jvm-build-service-e2e test job looks like

thoughts @stuartwdouglas ?

**Comment by stuartwdouglas** [comment]
I think this is ready to go in, and that plan for testing is pretty much what I had in mind. I have left all the sidecar build stuff in this PR for that reason.

**Pull request merged**
