### PR TITLE
fix: test with pre-kcp branch

### PR DESCRIPTION
**Pull request by psturc**
points to a ref from [this PR](https://github.com/redhat-appstudio/e2e-tests/pull/187)

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Note that I think we will also need this PR as well: https://github.com/redhat-appstudio/jvm-build-service/pull/232

**Comment by psturc** [comment]
> Note that I think we will also need this PR as well: #232

Good point. This means that this PR's CI checks will fail on [this line](https://github.com/redhat-appstudio/jvm-build-service/blob/c262e7b6ddf2ffe3fd29da77f05839299557ad9e/.ci/override-tekton-bundle.sh#L20)

Should we merge this PR and rerun CI in yours (https://github.com/redhat-appstudio/jvm-build-service/pull/232) or should I cherry pick your changes?

**Comment by psturc** [comment]
I went with cherry-picking

**Comment by psturc** [comment]
@stuartwdouglas @gabemontero all tests passed. are you happy to merge this?

once https://github.com/redhat-appstudio/e2e-tests/pull/187 is merged, we could switch back [the ref](https://github.com/redhat-appstudio/jvm-build-service/pull/234/files#diff-4e221a119c099486e562953f76eb14f8a4120c4bd2ba3f3158e13f49504e0104R102) to main branch, to get the latest changes from e2e-tests

**Pull request merged**
