### PR TITLE
update spi package

### PR DESCRIPTION
**Pull request by rsoaresd**
[Last update](https://github.com/redhat-appstudio/jvm-build-service/pull/717l) was not enough because it does not point to the latest changes (RemoteSecret is now in a separated repo).

After updating on e2e-tests repo, make local/cluster/prepares reports:
image

To fix this, the present PR updates the spi package

### CODE REVIEW

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
```
vendor/k8s.io/kube-openapi/pkg/cached/cache.go:242:16: undefined: atomic.Pointer
note: module requires Go 1.19 
```

This is blocked on https://github.com/openshift/release/pull/41333

@psturc FYI

**Comment by stuartwdouglas** [comment]
This won't pass until the openshift/release PR I linked is merged.

**Comment by stuartwdouglas** [comment]
You could try and make it pass by explicitly versioning  k8s.io/kube-openapi in go.mod, it is the indirect upgrade that is causing the failure.

**Comment by rsoaresd** [comment]
Thanks, @stuartwdouglas and @psturc

**Pull request merged**
