### PR TITLE
Change some sidecar memory settings

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by gabemontero** [comment]
in particular those maven localhost connection refused errors

**Comment by stuartwdouglas** [comment]
This will also need an infra deployments update, otherwise the sidecar there might have memory issues so 

/hold

**Comment by gabemontero** [comment]
> This will also need an infra deployments update, otherwise the sidecar there might have memory issues so
> 
> /hold

I will see if I can find cycles for ^^ today

**Comment by stuartwdouglas** [comment]
I would not update infra deployments until we know for sure what is going on. Something very weird is happening, and most of the actual exceptions that are displayed are after the build has finished (when the sidecar is shutting down).

**Comment by stuartwdouglas** [comment]
Let's just close this, and work on removing the sidecar altogether.

**Pull request closed without merging**
