### PR TITLE
Dump failures into their own directory

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by gabemontero** [comment]
I at least was not able to find an artifact subdir 

```
"/failed-dependency-builds/"
```

under the apicurio e2e subdir off of https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/202/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-apicurio-e2e/1565604328008323072 like @psturc was able to achieve with the e2e-tests for jvm-build.go

maybe he can provide a suggestion

**Comment by stuartwdouglas** [comment]
I am not sure what is going on here. In my initial test with a dummy file I saw the artifact being created, but it does not seem to be working now. I have added some more logging to see if I can figure out what is going on.

/test jvm-build-service-in-repo-apicurio-e2e

**Comment by stuartwdouglas** [comment]
It finally worked: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/202/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-in-repo-apicurio-e2e/1569097513166704640/artifacts/jvm-build-service-in-repo-apicurio-e2e/jvm-build-service-in-repo-apicurio-e2e/artifacts/failed-dependency-builds/

**Comment by stuartwdouglas** [comment]
Well sort of worked, so far only build discovery pods are being dumped.

**Pull request merged**
