### PR TITLE
Fix Gradle version selection

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Comment by gabemontero** [comment]
per our slack thread with @stuartwdouglas this evening @dwalluck should https://github.com/redhat-appstudio/jvm-build-service/blob/349efbb620ad011f0d59eda61f999623363613df/pkg/reconciler/dependencybuild/dependencybuild.go#L336 be adjusted as part of this?

**Comment by stuartwdouglas** [comment]
I will merge this as it improves things, but I have a PR coming in soon that will change the way this works (https://github.com/redhat-appstudio/jvm-build-service/pull/212).

**Comment by gabemontero** [comment]
> per our slack thread with @stuartwdouglas this evening @dwalluck should
> 
> https://github.com/redhat-appstudio/jvm-build-service/blob/349efbb620ad011f0d59eda61f999623363613df/pkg/reconciler/dependencybuild/dependencybuild.go#L336
> be adjusted as part of this?

OK https://github.com/redhat-appstudio/jvm-build-service/pull/212 is adjusting ^^

**Pull request merged**
