### PR TITLE
Change samples to use taskRunSpecs

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
LGTM !

**Review by gabemontero — APPROVED** [review]
jvm-build-service-e2e failed with our old connection closed friend accessing the maven proxy

see https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_jvm-build-service/219/pull-ci-redhat-appstudio-jvm-build-service-main-jvm-build-service-e2e/1565594433343197184/artifacts/jvm-build-service-e2e/jvm-build-service-e2e/artifacts/jvm-build-service-test/jvm-build-cvmx-pr-jvm-build-suite-component-bfie-rxtfg.log

that said, those component tests simply reference https://github.com/stuartwdouglas/hacbs-test-project and the devfile defined there

our in repo tests use the file affected here i.e. https://github.com/redhat-appstudio/jvm-build-service/blob/main/openshift-with-appstudio-test/e2e/jvm_build_service_test.go#L86 and they passed

I'm avoiding additional merges at the moment because I'm trying to get https://github.com/redhat-appstudio/infra-deployments/pull/658 merged before the kcp cut over in infra deps and additional  merges right now will disrupt that

feel free to merge @stuartwdouglas when you are back on the clock Monday

**Pull request merged**
