### PR TITLE
Initial work on local container based dev

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This will now enumerate the available artifacts on the server, which makes for much much faster builds (way faster than localstack).

At present this just enables local development flow, next step is to integrate into e2e and staging.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
The lack of sidecar logs is a real problem here, and it looks like it is crashing before logging is established.

**Comment by stuartwdouglas** [comment]
In repo tests are now passing

**Comment by stuartwdouglas** [comment]
@gabemontero this is green now, it would be great to get this in so we can start looking at using this for our e2e tests.

**Comment by gabemontero** [comment]
got a merge conflict now @stuartwdouglas

**Review by gabemontero — APPROVED** [review]

**Comment by gabemontero** [comment]
feel free to merge after your rebase and the tests getting green again ... just github approved

it is a US holiday on Monday so don't want for me to hit the merge button once ^^ occurs

**Comment by stuartwdouglas** [comment]
The JDK 17 build does appear to have actually completed (i.e. image was pushed), and the build controller only failed on 'show summary'.

I think this is as close to a green build we are going to get at the moment.

**Pull request merged**
