### PR TITLE
Enhance maven deploy to reference serverId and fix authentication/set…

### PR DESCRIPTION
**Pull request by rnc**
…tings.xml

For [JBS-50](https://issues.redhat.com//browse/JBS-50)

### CODE REVIEW

**Comment by rnc** [comment]
This currently isn't passing settings.xml through ; I think this would need #2224 and then something like https://github.com/redhat-appstudio/jvm-build-service/commit/5dc0a2d8941ce72fb92ec6f3d5837e17f4ae76e1

**Comment by ruhan1** [comment]
Looks good to me. Have you tried '-Dmaven.settings=path-to-custom-settings.xml'? for passing custom settings.xml location.

**Comment by rnc** [comment]
@ruhan1 Thats a good point ; I haven't; that would probably work as well as long as its passed via the task yaml params. I guess I was going for the argument value in https://github.com/redhat-appstudio/jvm-build-service/commit/5dc0a2d8941ce72fb92ec6f3d5837e17f4ae76e1 for consistency

**Comment by ruhan1** [comment]
Yeah, that looks good. pls merge them so I can try it.

**Review by matejonnet — APPROVED** [review]

**Pull request merged**
