### PR TITLE
Handle deployment in the cache

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This makes two major changes:
- The cache now handles deployment rather than the sidecar
- Contamination is now handled in a 'smart' manner, where builds are only considered contaminated if the contaminated artifacts are actually requested.

This contamination change means that it is no longer nessesary to fix contamination issues via ignoring artifacts, and it will prevent spurious builds from being kicked off that are not actually used by the main build.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@gabemontero FYI rather than removing the sidecar in one big hit I have decided to take an incremental approach. This is the first step that moves deployment to the cache. It ended up being bigger than just that, as the current deploy approach relied on a 'per build' config property to let you ignore contaminated artifacts that were not relevant, so I have had to change this to be an automated approach instead.

**Comment by gabemontero** [comment]
the apicurio failure at first glance appears unique / not a "typical" flake, though I only had time for a cursory / initial scan

perhaps related to this change @stuartwdouglas ?

**Comment by gabemontero** [comment]
actually I wonder if upstream apicurio has an issue, unless we have "sidecar" constraints

a couple of attempts with main branch against my local cluster produced a failure in the initial build against the final branch we are using from upstream.  From my local attempt:
```
[maven-run : mvn-goals] [INFO] Error stacktraces are turned on.
[maven-run : mvn-goals] [INFO] Scanning for projects...
[maven-run : mvn-goals] [INFO] Downloading from mirror.default: http://localhost:2000/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom
[maven-run : mvn-goals] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[maven-run : mvn-goals] [ERROR] Non-resolvable import POM: Could not transfer artifact io.quarkus:quarkus-bom:pom:2.7.6.Final from/to mirror.default (http://localhost:2000/maven2): Transfer failed for http://localhost:2000/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom 500 Internal Server Error @ line 473, column 25
[maven-run : mvn-goals]  @ 
[maven-run : mvn-goals] [ERROR] The build could not read 1 project -> [Help 1]
[maven-run : mvn-goals] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[maven-run : mvn-goals] [ERROR] Non-resolvable import POM: Could not transfer artifact io.quarkus:quarkus-bom:pom:2.7.6.Final from/to mirror.default (http://localhost:2000/maven2): Transfer failed for http://localhost:2000/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom 500 Internal Server Error @ line 473, column 25
[maven-run : mvn-goals] 
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:397)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
[maven-run : mvn-goals]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[maven-run : mvn-goals]     at java.lang.reflect.Method.invoke (Method.java:568)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[maven-run : mvn-goals] [ERROR]   
[maven-run : mvn-goals] [ERROR]   The project io.apicurio:apicurio-registry:2.2.4.Final (/workspace/source/pom.xml) has 1 error
[maven-run : mvn-goals] [ERROR]     Non-resolvable import POM: Could not transfer artifact io.quarkus:quarkus-bom:pom:2.7.6.Final from/to mirror.default (http://localhost:2000/maven2): Transfer failed for http://localhost:2000/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom 500 Internal Server Error @ line 473, column 25 -> [Help 2]
[maven-run : mvn-goals] org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact io.quarkus:quarkus-bom:pom:2.7.6.Final from/to mirror.default (http://localhost:2000/maven2): Transfer failed for http://localhost:2000/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom 500 Internal Server Error
[maven-run : mvn-goals]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:196)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1265)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:474)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:440)
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
[maven-run : mvn-goals]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[maven-run : mvn-goals]     at java.lang.reflect.Method.invoke (Method.java:568)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[maven-run : mvn-goals] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.quarkus:quarkus-bom:pom:2.7.6.Final from/to mirror.default (http://localhost:2000/maven2): Transfer failed for http://localhost:2000/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom 500 Internal Server Error
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:424)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[maven-run : mvn-goals]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1265)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:474)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:440)
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
[maven-run : mvn-goals]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[maven-run : mvn-goals]     at java.lang.reflect.Method.invoke (Method.java:568)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[maven-run : mvn-goals] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact io.quarkus:quarkus-bom:pom:2.7.6.Final from/to mirror.default (http://localhost:2000/maven2): Transfer failed for http://localhost:2000/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom 500 Internal Server Error
[maven-run : mvn-goals]     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
[maven-run : mvn-goals]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
[maven-run : mvn-goals]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[maven-run : mvn-goals]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute (BasicRepositoryConnector.java:644)
[maven-run : mvn-goals]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:262)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:499)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:401)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[maven-run : mvn-goals]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1265)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:474)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:440)
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
[maven-run : mvn-goals]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[maven-run : mvn-goals]     at java.lang.reflect.Method.invoke (Method.java:568)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[maven-run : mvn-goals] Caused by: org.apache.maven.wagon.TransferFailedException: Transfer failed for http://localhost:2000/maven2/io/quarkus/quarkus-bom/2.7.6.Final/quarkus-bom-2.7.6.Final.pom 500 Internal Server Error
[maven-run : mvn-goals]     at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:1196)
[maven-run : mvn-goals]     at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData (AbstractHttpClientWagon.java:1138)
[maven-run : mvn-goals]     at org.apache.maven.wagon.StreamWagon.getInputStream (StreamWagon.java:126)
[maven-run : mvn-goals]     at org.apache.maven.wagon.StreamWagon.getIfNewer (StreamWagon.java:88)
[maven-run : mvn-goals]     at org.apache.maven.wagon.StreamWagon.get (StreamWagon.java:61)
[maven-run : mvn-goals]     at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run (WagonTransporter.java:567)
[maven-run : mvn-goals]     at org.eclipse.aether.transport.wagon.WagonTransporter.execute (WagonTransporter.java:435)
[maven-run : mvn-goals]     at org.eclipse.aether.transport.wagon.WagonTransporter.get (WagonTransporter.java:412)
[maven-run : mvn-goals]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask (BasicRepositoryConnector.java:457)
[maven-run : mvn-goals]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:364)
[maven-run : mvn-goals]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[maven-run : mvn-goals]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute (BasicRepositoryConnector.java:644)
[maven-run : mvn-goals]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:262)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:499)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:401)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[maven-run : mvn-goals]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[maven-run : mvn-goals]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1265)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:474)
[maven-run : mvn-goals]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:440)
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)
[maven-run : mvn-goals]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[maven-run : mvn-goals]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[maven-run : mvn-goals]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
[maven-run : mvn-goals]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[maven-run : mvn-goals]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
[maven-run : mvn-goals]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[maven-run : mvn-goals]     at java.lang.reflect.Method.invoke (Method.java:568)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[maven-run : mvn-goals]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[maven-run : mvn-goals] [ERROR] 
[maven-run : mvn-goals] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[maven-run : mvn-goals] [ERROR] 
[maven-run : mvn-goals] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[maven-run : mvn-goals] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[maven-run : mvn-goals] [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[maven-run : mvn-goals] cat: /workspace/maven-settings/sidecar.log: No such file or directory
```

**Comment by stuartwdouglas** [comment]
This actually had a clean run yesterday, I just forgot to increase the upload file size limit so large builds failed on service registry.

**Comment by stuartwdouglas** [comment]
@gabemontero can you get any logs from those runs?

**Comment by gabemontero** [comment]
On Wed, Sep 14, 2022 at 5:23 PM Stuart Douglas ***@***.***>
wrote:

> @gabemontero <https://github.com/gabemontero> can you get any logs from
> those runs?
>
If you mean from the test’s collection of data no.  I did see some pod logs
for the service registry build in the gather extra section but it seems
incomplete.  That coupled with what I posted from my local run doesn’t make
sense to me at the moment

**Comment by gabemontero** [comment]
ok cool no conflicts after merging my deploy folder / infer image refs vs. config image refs reorg

**Review by gabemontero — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
I'll merge if the apicurio run comes back green (it is now running green again today in other PRs I have looked at this AM)

**Comment by gabemontero** [comment]
merging

`types.go:25: time: 2022-09-15 13:38:55.357754138 +0000 UTC m=+6846.666491704: dependencybuild FINAL created count: 117 complete count: 84, failed count: 31, contaminated count: 1`

**Pull request merged**
